### ISSUE TITLE
Question: how to change crosshair?????

### ISSUE THREAD

**Issue by Mmah2000** [Velaron/cs16-client#100]
Can you fix thats plz, request: we need a new small crosshair an x or a dot maybe . Can't wait for more updates im fan and thank you so much .

**Comment by xplshn** [comment]
Just set enable the xhair with the dot in the middle and set the gap and size to a negative number

**Comment by xplshn** [comment]
Change other parameters as needed.

**Comment by Mmah2000** [comment]
I didn't get a thing 😅 ! What r u talking bout plz ?

**Comment by Mmah2000** [comment]
> Just set enable the xhair with the dot in the middle and set the gap and size to a negative number
> 

I didn't get a thing 😅 ! What r u talking bout plz ?
