### ISSUE TITLE
The shield has incorrect culling (GL)

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [Velaron/cs16-client#11]
![image](https://user-images.githubusercontent.com/4449851/235445826-8ff181f2-022b-4c93-ac5e-4c3ab152b68f.png)

На вулкане проблемы нет

**Comment by Vladislav4KZ** [comment]
На Android такой баг не воспроизводится

Рендерер: OpenGL ES 2.0 (gl-wes-v2)

**Comment by Velaron** [comment]
Потому что я игрался с ним, в общем с этими щитами и ножами всё весело, и в каждой версии КС поведение другое) Куллинг ножа вообще сломан в движке и проявляется даже с оригинальным клиентом

**Comment by Vladislav4KZ** [comment]
> Теперь https://github.com/Velaron/cs16-client/issues/18#issuecomment-1551696193

У меня абсолютно то же самое, что на винде, что на андроиде.

**Comment by Velaron** [comment]
Fixed
