### ISSUE TITLE
Fog support with env_fog

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [Velaron/cs16-client#13]
Карта для теста: [test_fog_cs.zip](https://github.com/Velaron/cs16-client/files/11365145/test_fog_cs.zip) (env_fog)

Должно быть примерно так:
![image](https://user-images.githubusercontent.com/4449851/235447062-59a3414d-81bf-4313-8d51-8b1d68d88ae8.png)

**Comment by Velaron** [comment]
Thanks for the map, coming with next update
![image](https://user-images.githubusercontent.com/53096779/235632395-aa87ea39-9f5f-4002-b90b-9069cb7c8b87.png)

**Comment by Velaron** [comment]
On second thought, density seems wrong

**Comment by Velaron** [comment]
Start and end positions seem to be hardcoded as 100 and 2000, so that's probably OK, but I'm just asking to be sure

**Comment by 0x4E69676874466F78** [comment]
Забыл приложить [wad файл](https://github.com/0x4E69676874466F78/test_maps_for_hlrtx_project/raw/main/vulkan_debug.wad).
> On second thought, density seems wrong
> Start and end positions seem to be hardcoded as 100 and 2000, so that's probably OK, but I'm just asking to be sure

Проверил на актуальной стимовской контре, точно так же как у меня на скрине выше.
![image](https://user-images.githubusercontent.com/4449851/235639367-3a443d57-bf00-443d-8eca-2b03f283399c.png)

Так что это либо проблема в рендере тумана в ксаше либо надо что-то ещё подкрутить.

**Comment by 0x4E69676874466F78** [comment]
Ты ведь туман реализуешь через [(*FogParams)( float flDensity, int iFogSkybox ); ](https://github.com/FWGS/xash3d-fwgs/blob/d6d9011dcc92ea33eac41dc649de5bd7b7c514d4/engine/ref_api.h#L609)?

**Comment by Velaron** [comment]
да, FogParams + Fog, буду дальше тыкать тогда

**Comment by Velaron** [comment]
https://github.com/FWGS/xash3d-fwgs/issues/1188
Подозреваю связано с этим?

**Comment by Velaron** [comment]
На этот раз точно готово

**Comment by 0x4E69676874466F78** [comment]
Класс.
