### ISSUE TITLE
Не работает квар cl_corpsestay

### ISSUE THREAD

**Issue by Vladislav4KZ** [Velaron/cs16-client#17]
Вспомнил что недавно все задалбывали с этим багом в релизной версии CS16Client.

Трупы убитых врагов исчезают через несколько секунд после убийства, несмотря на то, какое значение указано в кваре ``mp_corpsestay``

**Comment by Velaron** [comment]
В этой версии проверял? В коммитах видел что птичка имплементил клиентские трупы

**Comment by Vladislav4KZ** [comment]
> В этой версии проверял? В коммитах видел что птичка имплементил клиентские трупы

Да, только что перепроверил на последнем тестовом билде CS16Client

**Comment by Velaron** [comment]
Перетести в некст билде, учти что значение квара не указывает точное время, в коде к значению прибавляется ещё секунд 10

**Comment by Vladislav4KZ** [comment]
Трупы теперь не исчезают сразу после смерти, но они теперь остаются даже в следующем раунде.

В оригинальной кс 1.6 трупы исчезают в новом раунде.
