### ISSUE TITLE
Pistols are in the left hand when the player is holding a shield (cl_righthand 1)

### ISSUE THREAD

**Issue by Vladislav4KZ** [Velaron/cs16-client#18]
Пистолеты находятся в левой руке когда игрок держит щит, при значении квара ``cl_righthand`` равному ``1``.

При ``cl_righthand 0`` когда игрок должен держать оружие в левой руке, он держит пистолеты в правой руке, а щит в левой.

**Comment by 0x4E69676874466F78** [comment]
Пистолет
![image](https://github.com/Velaron/cs16-client/assets/4449851/2931fc5d-0303-43d9-893d-39ad39ecacee)
Нож
![image](https://github.com/Velaron/cs16-client/assets/4449851/63b94e5e-992f-4869-802a-a713259f06eb)

**Comment by Vladislav4KZ** [comment]
> Пистолет
> ![image](https://github.com/Velaron/cs16-client/assets/4449851/2931fc5d-0303-43d9-893d-39ad39ecacee)
> Нож
> ![image](https://github.com/Velaron/cs16-client/assets/4449851/63b94e5e-992f-4869-802a-a713259f06eb)
> 

Спасибо, у меня почему-то изображения на загружались на GitHub.

**Comment by jeefo** [comment]
На сколько я помню м щит вообще не должен флипаться не зависимо от значения cl_righthand. Щит всегда слева, оружие справа.

**Comment by Velaron** [comment]
Верно, но это поведение менялось от версии до версии, возможно что-то сломали с релизом CZero, потому что раньше щит менял руку. Но в данном случае проблема с поведением cl_righthand лежит в движке, так как с оригинальным клиентом такие же баги.

**Comment by Velaron** [comment]
Fixed
