### ISSUE TITLE
В таблице счёта не отображаются никнеймы содержащие кириллицу

### ISSUE THREAD

**Issue by Vladislav4KZ** [Velaron/cs16-client#19]
Используется кодировка UTF-8 и шрифты с поддержкой кириллицы (gfx.wad, fonts.wad)

``cl_charset`` настроен на ``utf-8``
``hud_utf8`` настроен на ``1``

Вместо никнейма, содержащего кириллицу, отображается пустота с фрагами, смертями и пингом.

**Comment by Velaron** [comment]
Надеюсь пофикшено в некст билде
