### ISSUE TITLE
Cvars in cstrike.rc file always goes to their default values

### ISSUE THREAD

**Issue by Alprnn357** [Velaron/cs16-client#22]
I encountered that `numericalmenu`, `numericalmenu_clientonly` and `checkscoreboard` cvars goes to their default values. When their values changed then user quits,  engine doesn't save latest changes.
Also some varieties of `set` command like `seta`, `setu`, `setp`, `sets` etc. are missing that used to be used on cstrike.rc file of old cs16client.

**Comment by Velaron** [comment]
That's exactly why these variables are not working, and I'm not sure Xash3D needs that functionality back. I plan to replace these menus with a better implemenation later.

**Comment by Velaron** [comment]
These specific values should be saving for now
