### ISSUE TITLE
the userconfigd command is broken

### ISSUE THREAD

**Issue by Alprnn357** [Velaron/cs16-client#23]
Engine doesn't execute `touch_defalias.cfg` and `userconfig.cfg` in userconfig.d folder on startup. It shows the same effect when entering `userconfigd` command.
In the old cs16client engine, executes `userconfigd/touch_defalias.cfg` and `userconfigd/userconfig.cfg` files successfully on startup and by entering userconfigd command.

**Comment by Vladislav4KZ** [comment]
Doesn't reproduce for me.

Device: Samsung Galaxy A52 4G 4/128 (SM-A525F/DS)
OS: Android 13, OneUI 5.1

The engine successfully executes the configs from the userconfig.d folder at startup, and when entering the ``userconfigd`` command.

I've deleted the ``userconfig.d`` folder from ``cstrike`` and ``cstrike/custom`` and the engine also successfully executed configs from ``userconfig.d`` which are built into the CS16Client app.

**Comment by Alprnn357** [comment]
> Doesn't reproduce for me.
> 
> Device: Samsung Galaxy A52 4G 4/128 (SM-A525F/DS) OS: Android 13, OneUI 5.1
> 
> The engine successfully executes the configs from the userconfig.d folder at startup, and when entering the `userconfigd` command.
> 
> I've deleted the `userconfig.d` folder from `cstrike` and `cstrike/custom` and the engine also successfully executed configs from `userconfig.d` which are built into the CS16Client app.

I have updated cs16client app still fails to execute on me even when entering `userconfigd` command. The scoreboard button doesn't work because of this problem. I have to execute `userconfigd/touch_defalias.cfg` manually on the console or add to the `userconfig.cfg` to work properly

My device: Samsung Galaxy J7 2016 (SM-J710FQ) 2/16 4G/4.5G
OS: Android 8.1.0, Samsung Experience 9.5

**Comment by Velaron** [comment]
Are you using both Xash3D and CS16Client from github?

**Comment by Alprnn357** [comment]
I didn't update the app just uninstalled then installed latest android build.

**Comment by Velaron** [comment]
https://github.com/Velaron/xash3d-fwgs/releases/tag/continuous-android

**Comment by Vladislav4KZ** [comment]
> In the old cs16client engine, executes userconfigd/touch_defalias.cfg and userconfigd/userconfig.cfg

The new engine loads configs from the **userconfig.d** folder, not **userconfigd**. That's why loading configs doesn't work for you.

**Comment by Vladislav4KZ** [comment]
@Alprnn357 not a bug. The old engine also loads configs from the **userconfig.d** folder.

Use the proper folder name. **userconfigd** is the wrong name.

**Comment by Alprnn357** [comment]
> @Alprnn357 not a bug. The old engine also loads configs from the **userconfig.d** folder.
> 
> Use the proper folder name. **userconfigd** is the wrong name.

I have reinstalled cs16client latest version, xash3d latest version and the game data. It works right now. Thanks for replying.
