### ISSUE TITLE
VGUI-like scoreboard doesn't work

### ISSUE THREAD

**Issue by Vladislav4KZ** [Velaron/cs16-client#3]
При нажатии кнопки для открытия таблицы счёта игроков (scoreboard), конфиг выполняется, но таблица не появляется.

Работает только команда +showscores

**Comment by Velaron** [comment]
Пока что проверил только на ПК, и там работает

**Comment by Vladislav4KZ** [comment]
> Есть ещё какие-то варианты? На андроиде тоже не могу повторить

Это из-за того, что в ``cstrike.rc`` значение квара ``checkscoreboard`` задаётся командой ``seta`` которой нет в новом движке.

Scoreboard конфиг начинает работать, только после ввода в консоль ``set checkscoreboard 1``.

**Comment by Velaron** [comment]
Спасибо, исправлю
