### ISSUE TITLE
[Windows 10] Can't start new server though "Create game" menu.

### ISSUE THREAD

**Issue by CortexReaver** [Velaron/cs16-client#34]
Latest build of CS client with xash client as well:
![24-05-2023 162423](https://github.com/Velaron/cs16-client/assets/34350690/ee65ff98-21ca-4a73-b2ff-3235adbf697c)
Throwing this at me:
![24-05-2023 162452](https://github.com/Velaron/cs16-client/assets/34350690/041524eb-7e9f-443e-954f-a2a575ae6941)
Tested with 8684 and 9211 original counter-strike files from steam.

So as I understood, this client works well only with android atm. And I just have to wait a little, right?

**Comment by Velaron** [comment]
Try using the original mp.dll for now, I forgot to fix a bug for 32-bit Windows

**Comment by Velaron** [comment]
Fixed in the upcoming build
