### ISSUE TITLE
Increase Health & Ammo HUD limit

### ISSUE THREAD

**Issue by iQuitt** [Velaron/cs16-client#35]
As you know, the hud limit is 255 (HP). The bullet limit is also more complicated.. I just want to ask, can you raise this limit?

**Comment by Velaron** [comment]
Not possible without a custom server

**Comment by iQuitt** [comment]
> [@Velaron](https://github.com/Velaron) [@a1batross](https://github.com/a1batross)
> 
> Using this delta.lst on the client and server: https://github.com/rehlds/ReGameDLL_CS/blob/master/dist/delta.lst#L29
> 
> and this code: [ValveSoftware/halflife#2149 (comment)](https://github.com/ValveSoftware/halflife/issues/2149#issuecomment-795448109)
> 
> Would it not be possible to exceed 255 HP?

Just use healthinfo event. 
https://github.com/bariscodefxy/cs16-client/commit/4f5d3067a7a38a8ee529e5b28a3276afa64be189
