### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by Elinsrc** [Velaron/cs16-client#4]
Запускается через раз, или пока неостановиш движок, а иногда крашит

https://user-images.githubusercontent.com/99191833/231691896-1c292555-4c6e-40c7-be05-6a666e5d2c79.mp4

![Screenshot_20230413-124346](https://user-images.githubusercontent.com/99191833/231692079-8079405f-0d7f-4adb-9b13-e43c346c5c23.jpg)

**Comment by Vladislav4KZ** [comment]
Это проблема ксаша, он через раз запускается
