### ISSUE TITLE
[Windows] Game crashes when match starts with yapb installed.

### ISSUE THREAD

**Issue by CortexReaver** [Velaron/cs16-client#43]
Installation of yapb was done by this guide: https://yapb.readthedocs.io/en/latest/installation.html#installing-bot-on-windows
I can join team and chose class perfectly fine (through a console with jointeam and joinclass commands correspondingly), but when match is about to begin I get this (right after 00:01 on the timer):
![11-06-2023 100653](https://github.com/Velaron/cs16-client/assets/34350690/55f8f941-015e-40a1-bf95-b86cced4f690)

Game is filling all available player slots with bots, and it seems they are running around the map perfectly fine too until the match starts.

**Comment by a1batross** [comment]
This looks like an engine bug.

**Comment by a1batross** [comment]
@jeefo 

```
uint8_t *Game::getVisibilitySet (Bot *bot, bool pvs) {
   if (is (GameFlags::Xash3D)) {
      return nullptr;
   }
```

BUT WHY?

**Comment by jeefo** [comment]
Well, new engine still asserts, just the version of bot that is currently in releases can't detect new engine properly.

@CortexReaver install yapb from actions build: https://github.com/yapb/yapb/actions/runs/5269798983

**Comment by a1batross** [comment]
@jeefo the thing is, we care about mod compatibility. It's better to fix engine because such bug may occur in the other mods.

**Comment by a1batross** [comment]
https://github.com/FWGS/xash3d-fwgs/issues/834 and it sure does!

**Comment by a1batross** [comment]
I pushed an engine fix for this. https://github.com/FWGS/xash3d-fwgs/commit/4c02c255065e28938af35a2f1930495c090fdfdd

This probably can be back ported to the old engine as well. cc @tyabus
