### ISSUE TITLE
Прицел не отображается

### ISSUE THREAD

**Issue by DENCHIKTEAM** [Velaron/cs16-client#46]
Вне зависимости от оружия, настроек прицел в КС не отображается даже в меню настроек. Я проверял отображается ли прицел в ХЛ и там он рабочий.
![Screenshot_7](https://github.com/Velaron/cs16-client/assets/51756144/84caf7d8-4067-4187-874a-e04c4f3bb005)
![Screenshot_8](https://github.com/Velaron/cs16-client/assets/51756144/889fdabd-be56-45fd-83a9-527b5b735ffb)
![Screenshot_9](https://github.com/Velaron/cs16-client/assets/51756144/8c55006d-5730-4ff4-93c6-d2ea1b1fa79f)

**Comment by Velaron** [comment]
Теперь пропадать не должен
