### ISSUE TITLE
Can't use mouse on ingame menus

### ISSUE THREAD

**Issue by XxSIBxX** [Velaron/cs16-client#53]
On the windows 32bit build I am unable see my mouse or to use my mouse to select any buttons on all in game menus. I am also unable to use the "Menu item #" controls shown in the controls in the in game menus.
![image](https://github.com/Velaron/cs16-client/assets/80930278/b4ebbbcc-a236-4288-a7fa-f9f0aa1502c5)

**Comment by Velaron** [comment]
These are touch-only, you need to use the classic text menus on PC

**Comment by XxSIBxX** [comment]
> These are touch-only, you need to use the classic text menus on PC

How do I enable or use the text menus?

**Comment by DENCHIKTEAM** [comment]
main menu > play cs > customize > options > switch the buy menu type parameter from vgui menus to old style menus

**Comment by XxSIBxX** [comment]
> main menu > play cs > customize > options > switch the buy menu type parameter from vgui menus to old style menus
Thank you!
