### ISSUE TITLE
В меню Customize переключатели размера и цвета прицела не имеют текста при изначальном значении.

### ISSUE THREAD

**Issue by Vladislav4KZ** [Velaron/cs16-client#55]
Текст появляется только при нажатии на стрелки.

![Screenshot_20230910_192852_Xash3D FWGS (Test).png](https://github.com/Velaron/cs16-client/assets/22411953/1313fe11-674f-4027-b7cc-c291cab55f77)

Это было пофикшено в некоторых местах в этом коммите: https://github.com/FWGS/mainui_cpp/commit/53749736217b0c625a8b4a33f5aad279c9d2f97c

Но это не распространяется на настройки прицела.

**Comment by Velaron** [comment]
настройки прицела должны полностью работать (пока без отрисовки)
