### ISSUE TITLE
При броске гранаты, воспроизводится пердёж из помех радиосигнала непосредственно перед самой радиокомандой

### ISSUE THREAD

**Issue by Vladislav4KZ** [Velaron/cs16-client#6]
С другими радиокомандами такой хрени нет, это только при воспроизведении команды "Fire in the hole"

Видимо, эта радиокоманда воспроизводится три раза одновременно, из-за этого появляется данный эффект.

**Comment by EternalCringe** [comment]
Не знаю, у меня такой проблемы не наблюдалось. По крайней мере при игре по докальной сети

**Comment by Vladislav4KZ** [comment]
На локалке (listenserver) действительно этот баг не проявляется.

Он проявляется только на серверах из Internet games. Проверял конкретно на сервере, который запущен на новом движке.

**Comment by Vladislav4KZ** [comment]
Этот баг больше не воспроизводится.
