### ISSUE TITLE
Не работает кнопка тихой ходьбы +speed

### ISSUE THREAD

**Issue by Vladislav4KZ** [Velaron/cs16-client#86]
Проверял на тач пресете "phone_ahsim". При нажатии и удерживании кнопки со значком ноги, которая имеет команду ``+speed`` игрок при ходьбе всё ещё издаёт звуки.

Проверял на:
Xash3D FWGS v49/0.20
Номер сборки: 3387
Тип сборки: android-arm64
Коммит: https://github.com/FWGS/xash3d-fwgs/commit/1c84a5c8ade7cfac17d6b558669d4f721a0bf11f
Ветка: master

CS16Client
Номер сборки: 3118
Платформа: Android ARM64
Коммит: https://github.com/Velaron/cs16-client/commit/8879e7784a6e6ffcbee670c8acccf6080342614f

**Comment by Vladislav4KZ** [comment]
На ПК, нажимая клавишу SHIFT на клавиатуре, игрок ходит бесшумно.

А на Android я даже пробовал вводить команду ``+speed`` в консоль, и это не помогает.

**Comment by Vladislav4KZ** [comment]
А вообще, это косяк движка, а не CS16Client.

Это не зависит от запущенного мода на нём. На таче тихая ходьба не работает.

**Comment by a1batross** [comment]
На таче должно быть возможным ходить тихо слегка отклонив виртуальный джойстик. 

Но вообще-то +speed должен работать, это действительно баг.
