### ISSUE TITLE
Отображается неверный хэш и номер коммита в YaPB

### ISSUE THREAD

**Issue by Vladislav4KZ** [Velaron/cs16-client#89]
Если ввести в консоль команду ``yb version``, то там будет отображаться хэш и номер коммита из репозитория cs16-client а не из репозитория yapb.

**Comment by Vladislav4KZ** [comment]
Нашёл решение. Скоро сделаю патч в репозиторий yapb.

**Comment by 90999** [comment]
ARM64 下编译 yapb 会有出错，跳过可以继续成功编译 。

**Comment by Vladislav4KZ** [comment]
> ARM64 下编译 yapb 会有出错，跳过可以继续成功编译 。

I didn't have any errors when compiling YaPB for ARM64 even on the last commit from upstream.

**Comment by Vladislav4KZ** [comment]
Исправлено в https://github.com/yapb/yapb/commit/cf5a840e80ccf1ab4a682e07e734666cc4741e4f

Осталось просто обновить субмодуль YaPB.
