### ISSUE TITLE
Bump menu.dll to latest

### ISSUE THREAD

**Issue by Vad1mCSO2** [Velaron/cs16-client#95]
This bump must rebuild to latest to prevent crashes (e.g. Play CS > Customize)
Also adds key shortcuts in latest menu build

**Comment by Velaron** [comment]
Me clicking the link thinking it's a PR

**Comment by Vad1mCSO2** [comment]
![image](https://github.com/user-attachments/assets/f7011d07-3dd7-462e-b0a0-1d495455c678)
There are crash when opening customize

**Comment by Vladislav4KZ** [comment]
> There are crash when opening customize

Сan't reproduce in the menu taken from https://github.com/Velaron/cs16-client/releases/tag/continuous

**Comment by Vad1mCSO2** [comment]
> > There are crash when opening customize
> 
> Сan't reproduce in the menu taken from https://github.com/Velaron/cs16-client/releases/tag/continuous

I have already downloaded the latest continuous

**Comment by Vladislav4KZ** [comment]
@Vad1mCSO2 Is it because of the custom font and shell BMPs?

**Comment by Vad1mCSO2** [comment]
Shell only maybe

**Comment by Vladislav4KZ** [comment]
> Shell only maybe 

Send here your bmp files from the gfx/shell folder.
